schilljs_spacegame_planet_overview_controller:
    pattern: /overview
    defaults: { _controller: schilljs.spacegame.controller.planet:nyf }

schilljs_spacegame_planet_buildings_controller:
    pattern: /buildings
    defaults: { _controller: schilljs.spacegame.controller.planet:nyf }

schilljs_spacegame_planet_dockyard_controller:
    pattern: /dockyard
    defaults: { _controller: schilljs.spacegame.controller.planet:nyf }

schilljs_spacegame_planet_laboratory_controller:
    pattern: /laboratory
    defaults: { _controller: schilljs.spacegame.controller.planet:nyf }

schilljs_spacegame_planet_fleet_controller:
    pattern: /fleet
    defaults: { _controller: schilljs.spacegame.controller.planet:nyf }

