schilljs_spacegame_stats_users_controller:
    pattern: /users
    defaults: { _controller: schilljs.spacegame.controller.statistics:users, sort_key: 'total', sort_dir: 'desc' }

schilljs_spacegame_stats_users_sorted_controller:
    pattern: /users/{sort_key}/{sort_dir}
    defaults: { _controller: schilljs.spacegame.controller.statistics:users }

schilljs_spacegame_stats_alliances_controller:
    pattern: /alliances
    defaults: { _controller: schilljs.spacegame.controller.statistics:alliances, sort_key: 'total', sort_dir: 'desc', mode: '' }

schilljs_spacegame_stats_alliances_sorted_controller:
    pattern: /alliances/{sort_key}/{sort_dir}
    defaults: { _controller: schilljs.spacegame.controller.statistics:alliances, mode: '' }

schilljs_spacegame_stats_alliances_sorted_pm_controller:
    pattern: /alliances/{sort_key}/{sort_dir}/members
    defaults: { _controller: schilljs.spacegame.controller.statistics:alliances, mode: 'members' }
