schilljs_spacegame_alliance_overview_controller:
    pattern: /overview
    defaults: { _controller: schilljs.spacegame.controller.alliance:nyf }

schilljs_spacegame_alliance_found_controller:
    pattern: /found
    defaults: { _controller: schilljs.spacegame.controller.alliance:nyf }

schilljs_spacegame_alliance_manage_controller:
    pattern: /manage
    defaults: { _controller: schilljs.spacegame.controller.alliance:nyf }

schilljs_spacegame_alliance_users_controller:
    pattern: /users
    defaults: { _controller: schilljs.spacegame.controller.alliance:nyf }

schilljs_spacegame_alliance_forums_controller:
    pattern: /forums
    defaults: { _controller: schilljs.spacegame.controller.alliance:nyf }
