schilljs_spacegame_galaxy_favorites_controller:
    pattern: /favorites
    defaults: { _controller: schilljs.spacegame.controller.galaxy:favorites }

schilljs_spacegame_galaxy_favorites_add_controller:
    pattern: /favorites/add/{mquad}/{quad}/{planet}
    defaults: { _controller: schilljs.spacegame.controller.galaxy:add }
    requirements:
        mquad:   \d+
        quad:    \d+
        planet:  \d+

schilljs_spacegame_galaxy_favorites_remove_controller:
    pattern: /favorites/remove/{mquad}/{quad}/{planet}
    defaults: { _controller: schilljs.spacegame.controller.galaxy:remove }
    requirements:
        mquad:   \d+
        quad:    \d+
        planet:  \d+

schilljs_spacegame_galaxy_map_controller:
    pattern: /map
    defaults: { _controller: schilljs.spacegame.controller.galaxy:map, mquad: 0, quad: 0 }

schilljs_spacegame_galaxy_map_quad_controller:
    pattern: /map/{mquad}/{quad}
    defaults: { _controller: schilljs.spacegame.controller.galaxy:map }
    requirements:
        mquad:   \d+
        quad:    \d+
